CREATE EXTENSION if not exists  "uuid-ossp";
insert into patologia values 
(uuid_generate_v4(),'Ninguna','reciennacido'),
(uuid_generate_v4(),'Memb. Hialina','reciennacido'),
(uuid_generate_v4(),'Sind. Aspirat','reciennacido'),
(uuid_generate_v4(),'Apnea','reciennacido'),
(uuid_generate_v4(),'Otros Sdr','reciennacido'),
(uuid_generate_v4(),'Hemorragia','reciennacido'),
(uuid_generate_v4(),'Hiperbilirrub.','reciennacido'),
(uuid_generate_v4(),'Otros Hematol.','reciennacido'),
(uuid_generate_v4(),'Infecciones','reciennacido'),
(uuid_generate_v4(),'Defectos Congénitos','reciennacido'),
(uuid_generate_v4(),'Neurológicas','reciennacido'),
(uuid_generate_v4(),'Metab / Nutric.','reciennacido'),
(uuid_generate_v4(),'Otras','reciennacido'),
(uuid_generate_v4(),'Ninguna','parto'),
(uuid_generate_v4(),'Emb. Múltiple','parto'),
(uuid_generate_v4(),'Hipert. Previa','parto'),
(uuid_generate_v4(),'Pre Eclampsia','parto'),
(uuid_generate_v4(),'Eclampsia','parto'),
(uuid_generate_v4(),'Cardiopatia','parto'),
(uuid_generate_v4(),'Diabetes','parto'),
(uuid_generate_v4(),'Infección Urinaria','parto'),
(uuid_generate_v4(),'Otras Infecciones','parto'),
(uuid_generate_v4(),'Parasitosis','parto'),
(uuid_generate_v4(),'RCIU','parto'),
(uuid_generate_v4(),'Anem. Parto Pre.','parto'),
(uuid_generate_v4(),'Desprop. Cef. Pelv.','parto'),
(uuid_generate_v4(),'Hemorragia 1er Trimestre','parto'),
(uuid_generate_v4(),'Hemorragia 2do Trimestre','parto')
,(uuid_generate_v4(),'Hemorragia 3er Trimestre','parto')
